[tool.poetry]
name = "llm-twin"
version = "2.4.1"
package-mode = false
description = ""
authors = ["amartya pawar"]
license = "MIT"

[tool.poetry.dependencies]
#Core:
python = "~3.11"
click = "^8.2"
loguru = "^0.7"
rich = "^14"
numpy = "^2.2"
jinja2 = "^3.1"

#Database:
pymongo = "^4.14"
qdrant-client = "^1.18"

#Deep learning frameworks:
torch = "^2.8"
datasets = "^5.0"
s3fs = "<2026.7"
sentence-transformers = "^5.1"
tiktoken = "^0.11"

#ZenML
zenml = { version = "0.96.2", extras = ["server"] }


uvicorn = "^0.35"

#langchain
langchain = "^1.0"
langchain-community = "*"

langchain-openai = "*"
langchain-anthropic = "*"
langchain-google-genai = "*"
langchain-groq = "*"
langchain-mistralai = "*"
langchain-cohere = "*"
langchain-deepseek = "*"
langchain-perplexity = "*"

#Web crawlers:
selenium = "^4"
webdriver-manager = "^4"
chromedriver-autoinstaller = "^0.6"
beautifulsoup4 = "^4"
html2text = "*"
fake-useragent = "*"
jmespath = "^1"

#AWS:
sagemaker = "^2"
aws-profile-manager = "*"
kubernetes = "^33"
sagemaker-huggingface-inference-toolkit = "*"

#Miscelleaneous:
opik = "*"
stop-words = "*"
langchain-ollama = "^1.1.0"
langchain-qwq = "^0.3.5"
datasketch = "^2.0.0"
hnswlib = "^0.8.0"
transformers = "5.14.1"
sentencepiece = "^0.2.2"
einops = "^0.8.2"
accelerate = "^1.14.0"
streamlit = "^1.61.1"
google-api-python-client = "^2.198.0"
google-auth = "^2.56.3"
google-cloud-compute = "^1.50.0"
google-cloud-aiplatform = "^1.164.0"
google-cloud-storage = "^3.13.1"
google-cloud-artifact-registry = "^1.22.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8"
ruff = "^0.12"
pre-commit = "^4"
poethepoet = "^0.37"

[tool.ruff]
line-length = 88
target-version = "py311"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"


#Poe the Poet Configurations:
[tool.poe.tasks]

## Setting up docker infrastructure for MongoDB:

### Creating the Mongodb infrastructure:
local-docker-mongodb-infrastructure-up="docker compose -f configs/docker_configs/mongodb/mongo-compose.yaml up -d"

### Shutting the Mongodb infrastructure:
local-docker-mongodb-infrastructure-down="docker compose -f configs/docker_configs/mongodb/mongo-compose.yaml down"

## Setting up the Zenml Server:
set-local-stack="poetry run zenml stack set default"
local-zenml-server-down="poetry run zenml logout --local"
local-zenml-server-up="poetry run zenml login --local"

start-zenml-local=[
    "local-zenml-server-down",
    "local-zenml-server-up",
     "set-local-stack"
]

## Run Data ETL pipelines:
run-data-etl-user1="poetry run python -m pipelines.run_pipeline --run-etl --no-cache --etl-config-filename data_etl_user1.yaml"
run-data-etl-user2="poetry run python -m pipelines.run_pipeline --run-etl --no-cache --etl-config-filename data_etl_user2.yaml"
run-data-etl-user3="poetry run python -m pipelines.run_pipeline --run-etl --no-cache --etl-config-filename data_etl_user3.yaml"
run-data-etl-user4="poetry run python -m pipelines.run_pipeline --run-etl --no-cache --etl-config-filename data_etl_user4.yaml"

run-data-etl-pipeline=[
    "run-data-etl-user1",
    "run-data-etl-user2",
    "run-data-etl-user3",
    "run-data-etl-user4"
]

## Setting up docker infrastructure for Qdrant Vector Database

### Starting the Qdrant infrastructure:
local-docker-qdrant-infrastructure-up="docker compose -f configs/docker_configs/qdrant/qdrant-compose.yaml up -d"

### Shutting the Qdrant infrastructure:
local-docker-qdrant-infrastructure-down="docker compose -f configs/docker_configs/qdrant/qdrant-compose.yaml down"

## Run Rag Feature Pipeline:
run-rag-feature-pipeline="poetry run python -m pipelines.run_pipeline --run-rag-feature-pipeline --no-cache --rag-feature-pipeline-config-filename author_names.yaml"

## Run Instruct-Answer Dataset Generating Pipeline:
run-generate-instruct-dataset-pipeline="poetry run python -m pipelines.run_pipeline --run-generate-instruct-dataset-pipeline --no-cache --instruct-dataset-pipeline-config-filename author_names.yaml"

## Run Data Refinement Pipeline:
run-data-refinement-pipeline="poetry run python -m pipelines.run_pipeline --run-data-refinement-pipeline --no-cache --data-refinement-pipeline-config-filename config.yaml"

## Run Preference Dataset Generating Pipeline:
run-generate-preference-dataset-pipeline="poetry run python -m pipelines.run_pipeline --run-generate-preference-dataset-pipeline --no-cache --generate-preference-dataset-pipeline-config-filename author_names.yaml"

## Model Deployement on AWS:

### Create SageMaker Role:
create-sagemaker-role="poetry run python -m model_deployment.aws_deployment.roles.create_sagemaker_role"

### Create SageMaker Execution Role:
create-sagemaker-execution-role="poetry run python -m model_deployment.aws_deployment.roles.create_sagemaker_execution_role"

### Deploying Inference Endpoint on AWS SageMaker:
deploy-inference-endpoint-sagemaker="poetry run python -m model_deployment.aws_deployment.deploy"


## Model Deployement on GCP:

### Enabling Services for GCP Project:
enable-gcp-project-services="poetry run python -m model_deployment.gcp_deployment.infrastructure.enable_services"

### Deploying Inference Endpoint on Vertex AI:
deploy-inference-endpoint-vertex-ai="poetry run python -m model_deployment.gcp_deployment.deployment.deployment_service"

### Cleaning Up GCP Resources:
cleanup-gcp-resources="poetry run python -m model_deployment.gcp_deployment.cleanup_service.cleanup"

## Testing Deployed Model on GCP:
test-deployed-model-on-gcp="poetry run python -m model_inference.inference_using_gcp.llm_inference_vertex_endpoint"


## Start Uvicorn Web Server for FastAPI:
start-local-uvicorn-server="poetry run python -m application.server.start_uvicorn_server"


## Start Streamlit App:
start-streamlit-app="poetry run streamlit run application/streamlit/app.py"
