parameters:
  user_full_name: Raj Shamani
  links:
    #Substack
    - https://substack.com/@rajshamani/posts

    #LinkedIN
    - https://www.linkedin.com/in/rajshamani/recent-activity/all/

    #Threads
    - https://www.threads.com/@rajshamani

    #X
    - https://x.com/rajshamani

    #Medium
    - https://rajshamani.medium.com/gen-z-refuses-to-choose-between-stability-and-freedom-your-generation-did-who-ended-up-happier-4c283b75462a
    - https://rajshamani.medium.com/gen-z-hits-peak-burnout-at-25-their-parents-hit-it-at-42-heres-how-you-can-change-that-7b1a5560857a
    - https://rajshamani.medium.com/attention-is-no-longer-the-most-sought-after-currency-its-been-replaced-by-memory-979916dc26c9
    - https://rajshamani.medium.com/why-gen-z-blurring-the-personal-and-professional-lines-is-good-for-you-b452d321e937
    - https://rajshamani.medium.com/only-6-of-genz-want-to-be-leaders-the-real-problem-isnt-genz-2a08a04e8b6e