from loguru import logger
from pydantic import BaseModel,Field

from langchain_core.prompts import ChatPromptTemplate

from document_categories.rag_document_categories.query_document import Query
from rag.rag_steps.base.rag_step import RagStep
from rag.rag_steps.base.prompt_template_factory import PromptTemplateFactory

from utils.exceptions.model_exceptions.invalid_output_generation_exception import InvalidOutputGenerationException


class OutputSpecs(BaseModel):
    reconstructed_query:str=Field(description="The reconstructed query.")



class QueryReconstruction(RagStep,PromptTemplateFactory):
    @staticmethod
    def create_prompt() -> ChatPromptTemplate:
        template="""
        You are query reconstructor.
        You are provided with a query, your job is to reconstruct a query in such a way:
         - The reconstructed query is free of any metadata.
         - The reconstructed query is semantically similar to the original query.
        
        # Important Note:
         - You just have to remove the metadata in the query, not to change what it mean.
         - If there is no metadata in the query, then return it as it is.
        
        # Example:
         - Original Query: Hey, I am Paul Atrides. Can you write an article about Supervised Fine-tuning?
         - Reconstructed Query: Write an article about Supervised Fine-Tuning.
        
        # Query:
        {query}
        """

        prompt=ChatPromptTemplate.from_template(
            template=template,
            input_variable=["query"]
        )

        return prompt


    def generate(self,query:Query,*args,**kwargs) -> Query:
        query_content=query.content

        prompt=self.create_prompt()
        model=self.model
        model=model.with_structured_output(
            OutputSpecs
        )

        chain=prompt|model
        try:
            result=chain.invoke(
                {
                    "query":query_content
                }
            )

            if isinstance(result,OutputSpecs):
                reconstructed_query=result.reconstructed_query
                final_query=query.replace_content(new_content=reconstructed_query)

                logger.info("Query reconstructed successfully.")
                print(f"Original query: {query_content}")
                print(f"Reconstructed query: {reconstructed_query}")

                return final_query

            else:
                logger.info("Model generated invalid output!!!")
                raise InvalidOutputGenerationException("Invalid output generated by the model!!!")

        except Exception as e:
            logger.info(f"Exception encountered: {e}")
            raise

