from loguru import logger
from typing import List
from pydantic import BaseModel,Field

from langchain_core.prompts import ChatPromptTemplate

from document_categories.rag_document_categories.query_document import Query
from rag.rag_steps.base.rag_step import RagStep

from utils.exceptions.model_exceptions.invalid_output_generation_exception import InvalidOutputGenerationException


class OutputSpecs(BaseModel):
    expanded_queries:List[str]=Field("The list of expanded queries.")


class QueryExpansion(RagStep):
    @staticmethod
    def create_prompt() -> ChatPromptTemplate:
        template="""
        You are provided with a query, your job is to expand the query into {expand_to} queries in such a way that:
         - The expanded queries are semantically similar to the original query.
         - The expanded queries should provide multiple perspective to the original query.
         - The queries are expanded to retrieve more number of contexts from the vector database.
        
        # Example:
         - Original Query: Explain what is supervised fine tuning?
         - Expanded Queries: 
           - How supervised fine tuning is implemented?
           - When to use supervised fine tuning?
           - Give an code illustration of supervised fine tuning
        
        # Query:
        {query}
        """

        prompt=ChatPromptTemplate.from_template(
            template=template,
            input_variable=["expand_to","query"]
        )

        return prompt


    def generate(self,query:Query,*args,**kwargs) -> list[Query]:
        query_content=query.content
        expand_to=kwargs.get("expand_to",5)


        prompt=self.create_prompt()
        model=self.model
        model=model.with_structured_output(
            OutputSpecs
        )

        chain=prompt|model
        try:
            result=chain.invoke(
                {
                    "expand_to":expand_to,
                    "query":query_content
                }
            )

            if isinstance(result,OutputSpecs):
                expanded_queries=result.expanded_queries
                final_queries=[query]

                for expanded_query in expanded_queries:
                    final_query=query.replace_content(new_content=expanded_query)
                    final_queries.append(final_query)

                logger.info("Query Expansion Completed successfully.")
                print(f"Query expanded to {expand_to} new queries")
                print("Expanded Queries:")
                print(expanded_queries)

                return final_queries

            else:
                logger.info("Model generated invalid output!!!")
                raise InvalidOutputGenerationException("Invalid output generated by the model!!!")

        except Exception as e:
            logger.info(f"Exception encountered: {e}")
            raise





