from loguru import logger
from typing import Set,Literal
from pydantic import BaseModel,Field

from langchain_core.prompts import ChatPromptTemplate

from rag.rag_steps.base.rag_step import RagStep
from document_categories.rag_document_categories.query_document import Query

from utils.exceptions.model_exceptions.invalid_output_generation_exception import InvalidOutputGenerationException


class OutputSpecs(BaseModel):
    query_type:Set[Literal["Article", "Post", "Tweet", "Code", "None"]]=Field(description="""
    The type of documents helpful to answer the query.
    """)



class QueryRouter(RagStep):
    @staticmethod
    def create_prompt() -> ChatPromptTemplate:
        template="""
        You are a query router.
        You are provided with a query and you have to decide what kind of documents will be helpful as a context to answer the query.
        The type of documents available in the vector database are:
         - Article
         - Post
         - Tweet
         - Code
         - None (If you think none of the above mentioned document will be helpful to derive the answer.)
         
        # Important Note: 
         - You can return multiple values of document type.
         - Just return the document type and nothing else.
        
        # Query:
        {query}
        """

        prompt=ChatPromptTemplate.from_template(
            template=template,
            input_variable=["query"]
        )

        return prompt



    def generate(self,query:Query,*args,**kwargs) -> Query:
        prompt=self.create_prompt()

        model=self.model
        model=model.with_structured_output(
            OutputSpecs
        )

        query_content=query.content

        try:
            chain=prompt|model
            result=chain.invoke(
                {
                    "query":query_content
                }
            )

            if isinstance(result,OutputSpecs):
                query_type=result.query_type

                final_query=Query(
                    content=query.content,
                    query_type=query_type,
                    author_id=query.author_id,
                    author_full_name=query.author_full_name,
                    metadata=query.metadata
                )

                logger.info("Query routing completed successfully.")
                print(f"The type of documents to use as context for answering query are: {query_type}")

                return final_query

            else:
                logger.info("Model generated invalid output!!!")
                raise InvalidOutputGenerationException("Invalid output generated by the model!!!")


        except Exception as e:
            logger.info(f"Exception encountered: {e}")
            raise
