from loguru import logger
from uuid import UUID
from typing import Literal
from pydantic import BaseModel,Field

from langchain_core.prompts import ChatPromptTemplate

from document_categories.nosql_db_document_categories.base.user_document import UserDocument

from document_categories.rag_document_categories.query_document import Query
from rag.rag_steps.base.rag_step import RagStep

from utils.exceptions.model_exceptions.invalid_output_generation_exception import InvalidOutputGenerationException



class OutputSpecs(BaseModel):
    user_id:str|Literal["None"]=Field(description="The extracted user id from the query.")
    user_full_name:str|Literal["None"]=Field(description="The extracted user name from the query.")
    additional_metadata:dict[str,str]|Literal["None"]=Field(description="The extracted additional metadata.")



class SelfQuerying(RagStep):
    @staticmethod
    def create_prompt() -> ChatPromptTemplate:
        template="""
        You are provided with query, your job is to extract the metadata from the query.
        The metadata includes:
         - User Id
         - User Full Name
         - Additional metadata fields (such as date,platform name,etc.)
        
        # Important Note:
         - If you feel there is no metadata available then simply return 'None' for the respective fields.
        
        # Examples:
         - Query: Hey, I am Paul Atreides. Can you tell me about supervised fine-tuning?
         - Metadata:
            user_id: None
            user_full_name: Paul Atreides
            additional_metadata: None
        
        # Query:
        {query}
        """

        prompt=ChatPromptTemplate.from_template(
            template=template,
            input_variable=["query"]
        )

        return prompt


    def generate(self,query:Query,*args,**kwargs) -> Query:
        query_content=query.content

        prompt=self.create_prompt()
        model=self.model
        model=model.with_structured_output(
            OutputSpecs
        )

        chain=prompt|model
        try:
            result=chain.invoke(
                {
                    "query":query_content
                }
            )

            if isinstance(result,OutputSpecs):
                _id=result.user_id
                _name=result.user_full_name
                _additional_metadata=result.additional_metadata

                final_query=query
                if not _id=="None":
                    _id=UUID(_id,version=4)

                    user=UserDocument.get_or_create(
                        id=_id
                    )

                    final_query=Query(
                        content=query_content,
                        author_id=user.id,
                        author_full_name=user.full_name,
                        query_type=query.query_type
                    )

                elif not _name=="None":
                    name=_name.strip()
                    name=name.strip("\n")

                    name=name.split(" ")
                    first_name=name[0]
                    last_name=name[1]

                    user=UserDocument.get_or_create(
                        first_name=first_name,
                        last_name=last_name
                    )

                    final_query=Query(
                        content=query_content,
                        author_id=user.id,
                        author_full_name=user.full_name,
                        query_type=query.query_type
                    )

                if isinstance(_additional_metadata,dict):
                    final_query.metadata=_additional_metadata

                logger.info("Self Querying completed Successfully.")
                print(f"Original query: {query}")
                print(f"""
                Metadata Extracted:
                 - User ID: {_id}
                 - User Full Name: {_name}
                 - Additional Metadata: {_additional_metadata}
                """)

                return final_query


            else:
                logger.info("Model generated invalid output!!!")
                raise InvalidOutputGenerationException("Invalid output generated by the model!!!")

        except Exception as e:
            logger.info(f"Exception Encountered: {e}")
            raise


