from loguru import logger
from pydantic import BaseModel,Field

from langchain_core.prompts import ChatPromptTemplate
from langchain.chat_models import BaseChatModel
from langchain_mistralai import ChatMistralAI

from document_categories.rag_document_categories.conversation_summary_document import ConversationSummaryDocument
from utils.exceptions.model_exceptions.invalid_output_generation_exception import InvalidOutputGenerationException
from settings import Settings


class OutputSpecs(BaseModel):
    summary:str=Field("The generated summary.")



class ConversationSummaryHandler:
    model:BaseChatModel=ChatMistralAI(
        api_key=Settings.CONVERSATION_SUMMARY_GEN_MODEL_API_KEY,
        model_name=Settings.CONVERSATION_SUMMARY_GEN_MODEL_ID,
        temperature=Settings.CONVERSATION_SUMMARY_GEN_TEMP,
        max_retries=Settings.CONVERSATION_SUMMARY_GEN_MAX_RETRIES

    )

    @staticmethod
    def create_prompt() -> ChatPromptTemplate:
        template="""
        You are provided with a recent summary of conversation between the user and chat model along with their current conversation turn.
        Your job is to create a precised summary based on it.
        
        # Recent Summary:
        {recent_summary}
        
        # Conversation Turn:
        {conversation_turn}
        """

        prompt=ChatPromptTemplate.from_template(
            template=template,
            input_variable=["recent_summary","conversation_turn"]

        )

        return prompt


    def generate_summary(
            self,
            recent_summary:str,
            conversation_turn:str
    ) -> str:

        prompt=self.create_prompt()
        model=self.model
        model=model.with_structured_output(
            OutputSpecs
        )

        chain=prompt|model
        try:
            result=chain.invoke(
                {
                    "recent_summary":recent_summary,
                    "conversation_turn":conversation_turn
                }
            )

            if isinstance(result,OutputSpecs):
                generated_summary=result.summary
                return generated_summary

            else:
                logger.info("Model generated invalid output!!!")
                raise InvalidOutputGenerationException("Invalid output generated by the model!!!")


        except Exception as e:
            logger.info(f"Exception Encountered: {e}")
            raise


    @staticmethod
    def retrieve_summary() -> str:
        num_points=ConversationSummaryDocument.get_num_points_in_collection()
        if num_points==0:
            summary=""

        else:
            summary_doc=ConversationSummaryDocument.retrieve_point()
            summary=summary_doc.summary


        return summary


    def save_summary(self,user_content:str,model_content:str) -> None:
        conversation_turn=f"""
        User:
        {user_content}
        Model:
        {model_content}
        """

        num_points=ConversationSummaryDocument.get_num_points_in_collection()
        if num_points==0:
            generated_summary=self.generate_summary(
                recent_summary="",
                conversation_turn=conversation_turn
            )

            summary_doc=ConversationSummaryDocument(
                summary=generated_summary
            )
            ConversationSummaryDocument.bulk_insert(documents=[summary_doc])

        else:
            recent_summary_doc=ConversationSummaryDocument.retrieve_point()
            doc_id=str(recent_summary_doc.id)
            recent_summary=recent_summary_doc.summary

            generated_summary=self.generate_summary(
                recent_summary=recent_summary,
                conversation_turn=conversation_turn
            )

            ConversationSummaryDocument.update_point(
                point_id=doc_id,
                attribute="summary",
                updated_value=generated_summary
            )

